### ISSUE TITLE
wkt string validator

### ISSUE THREAD

**Issue by diatomsRcool** [diatomsRcool/water_body_checklists#1]
I have 99 wkt strings for water bodies and they are all returning 400. I cannot for the life of me find anything wrong with them. Is there a validator or something?

**Comment by jhpoelen** [comment]
It seems that there are two things going on - 

1. a version of ```checklist_script_gen.sh``` with a bug was copied and pasted into https://github.com/diatomsRcool/water_body_checklists. The bug was fixed in https://github.com/diatomsRcool/checklists/commit/ef924e24556ed790239e5a5f484923b64548adf3 , but did not propagate to the water checklists. 

I've donated some of my time to move the script ```checklist_script_gen.sh```   into https://github.com/effechecka/effechecka-scripts and make the checklists / water_body_checklists use it. 

Also, I've created an additional job in jenkins - this job only check the status of checklists every 10 minutes, making sure to keep the cluster busy creating checklists if needed see http://archive.guoda.bio/view/Effechecka%20Jobs/job/water%20body%20checklist%20status%20checker/ . The original job downloads entire checklists (if available) and runs only when the repository changes, or when triggered manually.

2. some wkt seems to be invalid - please see [checklist_status.tsv](http://archive.guoda.bio/view/Effechecka%20Jobs/job/water%20body%20checklist%20status%20checker/ws/checklist_status.tsv/*view*/) for checklists with status "400". They need some TLC.

Hope this helps!

**Comment by jhpoelen** [comment]
To help you troubleshoot your wktStrings, I've added some rudimentary error messages in the 400-bad request responses.

E.g., [water body checklist 3320](http://www.effechecka.org/?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=POLYGON%20%28%2840.43%2047.373%2C%2039.776%2047.205%2C%2039.431%2047.117%2C%2038.591%2046.86%2C%2038.166%2046.696%2C%2038.11%2046.392%2C%2038.254%2046.171%2C%2038.071%2045.971%2C%2037.615%2045.664%2C%2037.2%2045.335%2C%2036.723%2045.362%2C%2036.899%2045.26%2C%2036.413%2045.229%2C%2036.637%2045.378%2C%2035.961%2045.373%2C%2035.325%2045.392%2C%2034.815%2046.125%2C%2034.864%2045.94%2C%2034.902%2045.861%2C%2035.145%2045.55%2C%2035.304%2045.298%2C%2034.913%2045.681%2C%2034.771%2045.901%2C%2034.553%2045.84%2C%2034.64%2046.089%2C%2034.824%2046.19%2C%2035.339%2046.34%2C%2034.993%2046.094%2C%2036.154%2046.67%2C%2036.16%2046.535%2C%2036.793%2046.671%2C%2037.399%2046.955%2C%2037.977%2047.097%2C%2038.514%2047.193%2C%2038.94%2047.254%2C%2039.581%2047.207%2C%2039.341%2047.176%2C%2039.895%2047.263%2C%2040.43%2047.373%29%29) returns error message:

```
unsupported wktString [POLYGON ((40.43 47.373, 39.776 47.205, 39.431 47.117, 38.591 46.86, 38.166 46.696, 38.11 46.392, 38.254 46.171, 38.071 45.971, 37.615 45.664, 37.2 45.335, 36.723 45.362, 36.899 45.26, 36.413 45.229, 36.637 45.378, 35.961 45.373, 35.325 45.392, 34.815 46.125, 34.864 45.94, 34.902 45.861, 35.145 45.55, 35.304 45.298, 34.913 45.681, 34.771 45.901, 34.553 45.84, 34.64 46.089, 34.824 46.19, 35.339 46.34, 34.993 46.094, 36.154 46.67, 36.16 46.535, 36.793 46.671, 37.399 46.955, 37.977 47.097, 38.514 47.193, 38.94 47.254, 39.581 47.207, 39.341 47.176, 39.895 47.263, 40.43 47.373))]: Self-intersection at or near point (39.55196087036245, 47.20912923415439, NaN)
```

Also, see attached screenshot.

![screenshot from 2017-12-21 10-43-31](https://user-images.githubusercontent.com/1084872/34270081-d35dd264-e63b-11e7-9461-ea1fac04bbaa.png)

**Comment by diatomsRcool** [comment]
Ewww. that's bad. OK. I'll be working on this today.

**Comment by diatomsRcool** [comment]
A problem with some of these is wrap around, for example in the Pacific. Should I do two different polygons for these?

**Comment by jhpoelen** [comment]
Splitting the polygon to avoid the pole-wrapping would be a practical solution. As you probably now, pole-wrapping is not supported by spatial4j (https://github.com/locationtech/spatial4j), the software library used to figure out whether a lat/lng in inside or outside a polygon. With some more effort, we can probably devise some other spatial selection method.

**Comment by diatomsRcool** [comment]
All working now

**Comment by jhpoelen** [comment]
All are "200" now. . . cool! I hope the added features were helpful to troubleshoot the polygons.
